### ISSUE TITLE
沒有顯示選字表

### ISSUE THREAD

**Issue by lisean789** [tinycrate/gcantonese-ime#1]
Windows 22H2 版本可以成功安裝，但係輸入之後淨係英文字下面有底線，冇選字表出現。無辦法成功打到中文。
![image](https://user-images.githubusercontent.com/60573644/235047585-ca5301cd-b3c3-466d-966d-e4e7f0399dd8.png)
![image](https://user-images.githubusercontent.com/60573644/235047558-9e54f85a-3604-4d1a-8066-4ffacc568512.png)

**Comment by lisean789** [comment]
原來係我問題，但係想問有冇選項可以唔駛每次都要㩒space bar 先可以出選字單？

**Comment by tinycrate** [comment]
因為框架限制，暫時都需要㩒 space bar 先有選字單

**Comment by lisean789** [comment]
明白。點都好，多謝晒！
